# Generated by Django 5.1.3 on 2024-11-20 20:42

import RentEase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentEase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/', validators=[RentEase.models.validate_image_size]),
        ),
    ]
